[package]
name = "my_token2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.10.0"
solana-sdk = "1.10.0"
getrandom = { version = "0.2", features = ["js"] }